[package]
name = "ovhl-engine/v2"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.2.0" # Atau 0.3 tergantung preferensi, kita default 0.2 stabil
Promise = "evaera/promise@4.0.0"
