[package]
name = "ovhl-engine/v2"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.3.0"
Promise = "evaera/promise@4.0.0"
topbarplus = "1foreverhd/topbarplus@3.4.0"